#!/bin/bash
# Script: mymount
# This script mounts or unmounts my local NFS ISO share
# Create a hard or soft link to mount-isos called unmount-isos

## Define some variables
# Paths on NAS
nasserver="nas.tehmonk.com"
nasbase="/mnt/vit-nas1"
nasbackups="$nasserver:$nasbase/backups"
nasisos="$nasserver:$nasbase/LAN-Storage/ISO_Store"
nasshares="$nasserver:$nasbase/LAN-Storage/ShareData"

# Local paths
localbackups="/home/daryl/lanshares/backups"
localisos="/home/daryl/lanshares/iso_store"
localshares="/home/daryl/lanshares/sharedata"

# get command that launched this script
mycommand="$(basename $0)"

## Functions
# help function
help() {
  # Display Help
  echo "This command will mount or unmount a specified remote"
  echo
  echo "Syntax: mymount|myunmount <mount name>"
  echo "mounts names:"
  echo "  backups   NFS share from NAS for docs and working files"
  echo "  isos      NFS share from NAS for OS ISO images"
  echo "  shares    NFS share from NAS for various LAN shared directories"
  echo "  all       All three of the above shares"
  echo
  echo "  help      Prints this message."
}

## Script Prerequisites
# Script must be run as root or with sudo
user=$(id -u)
#echo $user

if [[ $user > 0 ]];
then
  echo "This command requires root. Use sudo or switch to root"
  exit
fi

# No arguments and more than 1 arguments should print a help msg
if [[ $# -lt 1 ]] || [[ $# -gt 1 ]]; then
  echo "Must have one arguement to determine which mount we are operating on"
  help
  exit
fi

# which mount are we working on?
case $1 in
  backups)
    naspath="$nasbackups"
    localpath="$localbackups"
    ;;
  isos)
    naspath="$nasisos"
    localpath="$localisos"
    ;;
  shares)
    naspath="$nasshares"
    localpath="$localshares"
    ;;
  all)
    naspath=("$nasbackups" "$nasisos" "$nasshares")
    localpath=("$localbackups" "$localisos" "$localshares")
    ;;
  *)
    help
    ;;
esac

# if called with mymount, mount the share
# if called with unmount, unmount the share
# a link must be made to mymount called myunmount
if [[ ${#naspath[@]} -eq ${#localpath[@]} ]]; then
  for i in ${!naspath[@]}; do
    if [[ $mycommand == "mymount" ]];
    then
      if [ ! -d ${localpath[$i]} ]; then
        mkdir ${localpath[$i]} || echo "${localpath[$i]} does not exist and I cannot make it"; exit
      fi
      mount -o tcp,vers=3 -t nfs ${naspath[$i]} ${localpath[$i]} || echo "Failed to mount $1 at ${localpath[$i]}"
    elif [[ $mycommand == "myunmount" ]];
    then
      umount ${localpath[$i]} || echo "Failed to unmount ${localpath[$i]}"
    else
      echo "I don't know how we got here. "'$mycommand'" isn't looking good"
      exit
    fi
  done
else
  echo "Something went wrong!"
  echo "Time to troubleshoot the script."
  echo '$naspath does not have the same number of items as $localpath'
fi
